DROP TABLE IF EXISTS gifcomments;

CREATE TABLE IF NOT EXISTS gifcomments(
	id SERIAL NOT NULL PRIMARY KEY,
	gifid INTEGER NOT NULL REFERENCES gifs(id) ON DELETE CASCADE,
	userid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	comment TEXT NOT NULL,
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);