DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
	id SERIAL NOT NULL PRIMARY KEY,
	firstname VARCHAR(100) NOT NULL,
	lastname VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR NOT NULL,
	gender VARCHAR(15),
	jobrole VARCHAR(20) NOT NULL,
	department VARCHAR(100) NOT NULL,
	address VARCHAR(100) NOT NULL
);