language: node_js
node_js:
  - 12.13.1
env:
  - NODE_ENV=testing
cache: npm
install:
  - npm ci
services:
  - postgresql
before_script:
  - psql -c 'create database teamwork_test_db;' -U postgres
script:
  - npm run test
  - npm run report-coverage
