DROP TABLE IF EXISTS articles;

CREATE TABLE IF NOT EXISTS articles(
	id SERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	article TEXT NOT NULL,
	created_on TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);