
CREATE TABLE IF NOT EXISTS users(
	id SERIAL NOT NULL PRIMARY KEY,
	firstname VARCHAR(100) NOT NULL,
	lastname VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR NOT NULL,
	gender VARCHAR(15),
	jobrole VARCHAR(20) NOT NULL,
	department VARCHAR(100) NOT NULL,
	address VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS articles(
	id SERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	article TEXT NOT NULL,
	created_on TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS articlecomments(
	id SERIAL NOT NULL PRIMARY KEY,
	articleid INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
	userid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	comment TEXT NOT NULL,
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gifs(
	id SERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	public_id VARCHAR(255) NOT NULL,
	size VARCHAR(255) NOT NULL,
	imageurl VARCHAR(255) NOT NULL,
	created_on TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS gifcomments(
	id SERIAL NOT NULL PRIMARY KEY,
	gifid INTEGER NOT NULL REFERENCES gifs(id) ON DELETE CASCADE,
	userid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	comment TEXT NOT NULL,
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);