DROP TABLE IF EXISTS articlecomments;

CREATE TABLE IF NOT EXISTS articlecomments(
	id SERIAL NOT NULL PRIMARY KEY,
	articleid INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
	userid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	comment TEXT NOT NULL,
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);