DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS comments(
	id SERIAL NOT NULL PRIMARY KEY,
	articleId INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
	userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	comment TEXT NOT NULL,
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);